apiVersion: apps/v1
kind: Deployment
metadata:
  name: nest-sensor
  namespace: home-sensors
spec:
  replicas: 1
  revisionHistoryLimit: 1
  selector:
    matchLabels:
      app: nest-sensor
  template:
    metadata:
      labels:
        app: nest-sensor
    spec:
      imagePullSecrets:
        - name: ghcr-kj800x
      containers:
        - name: nest-sensor
          image: ghcr.io/kj800x/nest-influxdb-integration:commit-$SHA
          command: ["/bin/sh", "-c", "node lib/index.js"]
          env:
            - name: NODE_ENV
              value: "production"
            - name: METRICS_PORT
              value: "9100"
            - name: GOOGLE_REFRESH_TOKEN
              valueFrom:
                secretKeyRef:
                  name: google-nest-sensor-auth
                  key: GOOGLE_REFRESH_TOKEN
            - name: GOOGLE_CLIENT_ID
              valueFrom:
                secretKeyRef:
                  name: google-nest-sensor-auth
                  key: GOOGLE_CLIENT_ID
            - name: GOOGLE_CLIENT_SECRET
              valueFrom:
                secretKeyRef:
                  name: google-nest-sensor-auth
                  key: GOOGLE_CLIENT_SECRET
          ports:
            - containerPort: 9100
              protocol: TCP
          livenessProbe:
            httpGet:
              path: /
              port: 9100
            initialDelaySeconds: 5
            periodSeconds: 10
            timeoutSeconds: 2
            failureThreshold: 3
          volumeMounts:
            - name: access-token-dir
              mountPath: /app/data
          workingDir: "/app"
      volumes:
        - name: access-token-dir
          nfs:
            server: 10.60.1.15
            path: /data/services/nest-scrape






